// # Environtment variables

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter();
  console.log(process.env.NEXT_PUBLIC_ANALYTICS_ID);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => {
        router.push("/a")
      }}>Test</button>
    </div>
  )
}

export async function getStaticProps() {
  console.log(process.env.HOSTNAME);
  console.log(process.env.HOST);
  return {
    props: {}
  }
}