import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Box, Button, Heading, Text, useStyleConfig } from "@chakra-ui/react";

const useStyles = (props: any) => ({
  testing: {
    color: "blue",
  }
})

export default function Home() {
  const a = 1;
  const classes = useStyles({a});

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href={"/user"}>User</Link>
        <Text color='primary'>
          màu đổi tùy
        </Text>
        <Box bg="brand.100">Welcome</Box>
        {/* colorScheme tự lấy name.500 nên phải specific 500 mới được */}
        <Button colorScheme='brand'>Click me</Button>
        <Button size='xl' variant='with-shadow' style={{backgroundColor: "red"}}>
          Welcome
        </Button>

        <Button style={classes.testing}>Test</Button>
        
        <Box borderWidth={2} borderColor='purple.500' p={5} className='my-box'>
          <Heading size='lg'>
            Hover the box...
            <Box
              as='span'
              color='red.500'
              sx={{
                '.my-box:hover &': {
                  color: 'green.500',
                },
              }}
            >
              And I will turn green
            </Box>
          </Heading>
        </Box>
      </main>
    </div>
  );
}
